/*
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
}
