/*
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl

import org.eclipse.xtext.ISetup

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DslStandaloneSetup extends DslStandaloneSetupGenerated {

	def static void doSetup() {
		new DslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
	
