<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="orm" nsURI="http://orm/1.0" nsPrefix="org.framed.orm.model">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" interface="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Model" eOpposite="#//Model/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundary" eType="#//geometry/Rectangle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingRelations" eType="#//Relation"
        eOpposite="#//Relation/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingRelations" eType="#//Relation"
        eOpposite="#//Relation/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencingElement" eType="ecore:EClass ../../org.rosi.crom.metamodel/src-gen/crom_l1_composed.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" eType="ecore:EClass ../../org.rosi.crom.metamodel/src-gen/crom_l1_composed.ecore#//ModelElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true" eOpposite="#//Relation/relationContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true" eOpposite="#//ModelElement/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationContainer" lowerBound="1"
        eType="#//Model" eOpposite="#//Model/relations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ModelElement"
        eOpposite="#//ModelElement/incomingRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ModelElement"
        eOpposite="#//ModelElement/outgoingRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="#//geometry/RelativePoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencingElement" eType="ecore:EClass ../../org.rosi.crom.metamodel/src-gen/crom_l1_composed.ecore#//Relation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//Relation #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondParthood" lowerBound="1"
        defaultValueLiteral="Unconstrained"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondLower" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstLower" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstUpper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondUpper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstParthood" lowerBound="1"
        defaultValueLiteral="Unconstrained"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLabel" lowerBound="1"
        eType="#//RelationLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLabel" lowerBound="1"
        eType="#//RelationLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstLowerUpper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondLowerUpper" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rlshipConstraints" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationLabel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0..1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelationEnd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eSubpackages name="geometry">
    <eClassifiers xsi:type="ecore:EClass" name="Point">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rectangle">
      <eStructuralFeatures xsi:type="ecore:EReference" name="topLeft" eType="#//geometry/Point"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bottomRight" eType="#//geometry/Point"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelativePoint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencePoints" lowerBound="2"
          upperBound="2" eType="#//geometry/Point"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distances" lowerBound="2"
          upperBound="2" eType="#//geometry/Point" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
