/**
 *
 * $Id$
 */
package org.framed.orm.model.validation;

import org.eclipse.emf.common.util.EList;

import org.framed.orm.model.ModelElement;
import org.framed.orm.model.Shape;

/**
 * A sample validator interface for {@link org.framed.orm.model.Model}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can
 * be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
  boolean validate();

  boolean validateElements(EList<ModelElement> value);

  boolean validateParent(Shape value);
}
