/**
 *
 * $Id$
 */
package org.framed.orm.model.validation;

import org.eclipse.emf.common.util.EList;

import org.framed.orm.geometry.RelativePoint;

import org.framed.orm.model.ModelElement;
import org.framed.orm.model.NamedElement;
import org.framed.orm.model.Relation;
import org.framed.orm.model.Shape;

/**
 * A sample validator interface for {@link org.framed.orm.model.Relation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationValidator {
	boolean validate();

	boolean validateTarget(ModelElement value);

	boolean validateSource(ModelElement value);

	boolean validateBendpoints(EList<RelativePoint> value);

	boolean validateSourceLabel(NamedElement value);

	boolean validateTargetLabel(NamedElement value);

	boolean validateReferencedRelation(EList<Relation> value);

	boolean validateReferencedRoles(EList<Shape> value);

	boolean validateReferencedRelation(Relation value);
}
