/**
 *
 * $Id$
 */
package org.framed.orm.model.validation;

import org.framed.orm.geometry.Rectangle;

import org.framed.orm.model.Model;
import org.framed.orm.model.NamedElement;
import org.framed.orm.model.Segment;

/**
 * A sample validator interface for {@link org.framed.orm.model.Shape}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShapeValidator {
	boolean validate();

	boolean validateFirstSegment(Segment value);

	boolean validateSecondSegment(Segment value);

	boolean validateModel(Model value);

	boolean validateDescription(NamedElement value);

	boolean validateBoundaries(Rectangle value);
}
