/**
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl.generator;

import java.io.ByteArrayOutputStream;
import java.util.Collections;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class DslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      final Resource.Factory.Registry registry = Resource.Factory.Registry.INSTANCE;
      final Map<String, Object> extensionToFactoryMap = registry.getExtensionToFactoryMap();
      XMIResourceFactoryImpl _xMIResourceFactoryImpl = new XMIResourceFactoryImpl();
      extensionToFactoryMap.put("editpolicy", _xMIResourceFactoryImpl);
      URI _uRI = resource.getURI();
      URI _trimFileExtension = _uRI.trimFileExtension();
      final URI xmiUri = _trimFileExtension.appendFileExtension("xmi");
      final ResourceSetImpl outResourceSet = new ResourceSetImpl();
      final Resource outResource = outResourceSet.createResource(xmiUri);
      EList<EObject> _contents = outResource.getContents();
      EList<EObject> _contents_1 = resource.getContents();
      _contents.addAll(_contents_1);
      final ByteArrayOutputStream outBuffer = new ByteArrayOutputStream();
      outResource.save(outBuffer, Collections.EMPTY_MAP);
      String _lastSegment = xmiUri.lastSegment();
      String _string = outBuffer.toString();
      fsa.generateFile(_lastSegment, _string);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
