/*
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
