/*
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/framed/orm/editPolicy/model/dsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
