/**
 * generated by Xtext 2.10.0
 */
package org.framed.orm.editPolicy.model.dsl;

import org.framed.orm.editPolicy.model.dsl.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
